### ISSUE TITLE
Time cost of PTGM

### ISSUE THREAD

**Issue by ericccq** [PKU-RL/PTGM#4]
Hi,thank you for the effort on opening source. 

I have successfully run the code, however, MineDojo env takes a lot of time during the whole process.
It seems impossible to finish the whole training with single CPU running MineDojo.

Could you please tell me the PTGM's total time cost and hardware scale for training 1e6 episodes?

**Comment by YHQpkueecs** [comment]
Hi! We run experiments on an RTX 4090 GPU with Intel i9 CPU. MineDojo runs at ~20fps and training 1e6 steps takes ~12h. (We train for 1e6 steps, not 1e6 episodes.)
