### ISSUE TITLE
[HELP] Goal input in Goal conditioned policy

### ISSUE THREAD

**Issue by ZijunSong** [PKU-RL/PTGM#5]
Hello, 

I am a newcomer and I am currently trying to follow your excellent paper. I noticed in the model architecture diagram that the Goal Conditioned Policy can take both the goal and observation as inputs to output an action. However, I couldn't find the part in the Python code related to the `bash steve1/train_goal_conditioned_policy.sh` script where the model is pretrained to accept the goal input. 

I would greatly appreciate it if you could clarify this for me!

Thank you in advance!

**Comment by YHQpkueecs** [comment]
Hi! Please see `steve1/embed_conditioned_policy.py`. `line 218`: In the `forward` of the policy network, we add the current image's representation and the transformed MineCLIP embedding of the goal image to feed into the Transformer.
